[package]
name = "howl-server"
version = "0.1.0"
edition = "2021"

[dependencies]
libhowl = { path = "../libhowl" }
clap = { version = "3.1.18", features = ["derive"] }
env_logger = "0.9.0"
tokio = { version = "1", features = ["full"] }